<a href="https://colab.research.google.com/github/VishnuBhaarath/Handwritten-digits-neural-net-classification/blob/master/Neuralnet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
import seaborn as seabornInstance 
from sklearn import metrics
from scipy.io import loadmat

In [0]:
data = loadmat('ex3data1.mat')

In [0]:
X=data['X']

In [7]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [8]:
X.shape

(5000, 400)

In [0]:
Y=data['y']

In [10]:
Y #The output layer representing numbers for each examples, there are 5000 rows, each representing a number from 0 to 10

array([[10],
       [10],
       [10],
       ...,
       [ 9],
       [ 9],
       [ 9]], dtype=uint8)

In [11]:
Y.shape

(5000, 1)

In [0]:
theta= loadmat('ex3weights.mat')

In [0]:
Theta1=theta['Theta1'] #Retreving the stored values of Theta1 from ex3weights.mat
Theta2=theta['Theta2'] #Retreving the stored values of Theta2 from ex3weights.mat

In [17]:
Theta1  

array([[-2.25623899e-02, -1.05624163e-08,  2.19414684e-09, ...,
        -1.30529929e-05, -5.04175101e-06,  2.80464449e-09],
       [-9.83811294e-02,  7.66168682e-09, -9.75873689e-09, ...,
        -5.60134007e-05,  2.00940969e-07,  3.54422854e-09],
       [ 1.16156052e-01, -8.77654466e-09,  8.16037764e-09, ...,
        -1.20951657e-04, -2.33669661e-06, -7.50668099e-09],
       ...,
       [-1.83220638e-01, -8.89272060e-09, -9.81968100e-09, ...,
         2.35311186e-05, -3.25484493e-06,  9.02499060e-09],
       [-7.02096331e-01,  3.05178374e-10,  2.56061008e-09, ...,
        -8.61759744e-04,  9.43449909e-05,  3.83761998e-09],
       [-3.50933229e-01,  8.85876862e-09, -6.57515140e-10, ...,
        -1.80365926e-06, -8.14464807e-06,  8.79454531e-09]])

In [18]:
Theta2

array([[-0.76100352, -1.21244498, -0.10187131, -2.36850085, -1.05778129,
        -2.20823629,  0.56383834,  1.21105294,  2.21030997,  0.44456156,
        -1.18244872,  1.04289112, -1.60558756,  1.30419943,  1.37175046,
         1.74825095, -0.23365648, -1.52014483,  1.15324176,  0.10368082,
        -0.37207719, -0.61530019, -0.1256836 , -2.27193038, -0.71836208,
        -1.29690315],
       [-0.61785176,  0.61559207, -1.26550639,  1.85745418, -0.91853319,
        -0.05502589, -0.38589806,  1.29520853, -1.56843297, -0.97026419,
        -2.18334895, -2.85033578, -2.07733086,  1.63163164,  0.3490229 ,
         1.82789117, -2.44174379, -0.8563034 , -0.2982564 , -2.07947873,
        -1.2933238 ,  0.89982032,  0.28306578,  2.31180525, -2.46444086,
         1.45656548],
       [-0.68934072, -1.94538151,  2.01360618, -3.12316188, -0.2361763 ,
         1.38680947,  0.90982429, -1.54774416, -0.79830896, -0.65599834,
         0.7353833 , -2.58593294,  0.47210839,  0.55349499,  2.51255453,
       

In [0]:
t=np.ones([5000, 1], dtype = int) 

In [34]:
inputlayer = np.column_stack((t, X))   #Adding biasing to X
inputlayer

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [22]:
inputlayer.shape

(5000, 401)

In [23]:
Theta1.shape

(25, 401)

In [0]:
z1=np.dot(Theta1, np.transpose(inputlayer))

In [25]:
z1.shape

(25, 5000)

In [0]:
h1=1 / (1 + np.exp(-z1)) #Finding the sigmoid. 

In [28]:
h1

array([[5.03618685e-02, 8.05782163e-03, 1.41949887e-02, ...,
        2.96781175e-01, 8.51205095e-01, 9.72262381e-01],
       [7.93957162e-02, 5.10486829e-02, 2.44354705e-02, ...,
        7.32901746e-01, 3.58434539e-01, 5.48598771e-06],
       [9.93001966e-01, 9.33671593e-01, 9.97518887e-01, ...,
        1.57724076e-01, 1.83675450e-01, 9.93379633e-01],
       ...,
       [9.72517962e-01, 8.91385592e-01, 8.24334311e-01, ...,
        8.60396828e-01, 9.84854863e-01, 9.99235749e-01],
       [9.43421623e-01, 9.90982126e-01, 9.56466386e-01, ...,
        3.98474223e-02, 2.75399966e-01, 8.96120297e-01],
       [1.07213787e-01, 5.94701645e-02, 8.86760824e-02, ...,
        1.51177198e-01, 4.35605471e-02, 5.00966928e-02]])

In [0]:
hiddenlayer = np.column_stack((t, np.transpose(h1))) #Adding biasing to the hidden layer.

In [30]:
hiddenlayer.shape

(5000, 26)

In [0]:
z2=np.dot(Theta2,np.transpose(hiddenlayer))

In [0]:
h2=1 / (1 + np.exp(-z2))

In [35]:
h2 # The final output layer

array([[1.12661530e-04, 4.79026796e-04, 8.85702310e-05, ...,
        5.17641791e-02, 8.30631310e-04, 4.81465717e-05],
       [1.74127856e-03, 2.41495958e-03, 3.24266731e-03, ...,
        3.81715020e-03, 6.22003774e-04, 4.58821829e-04],
       [2.52696959e-03, 3.44755685e-03, 2.55419797e-02, ...,
        2.96297510e-02, 3.14518512e-04, 2.15146201e-05],
       ...,
       [4.01468105e-04, 2.39107046e-03, 6.22892325e-02, ...,
        2.15667361e-03, 1.19366192e-02, 5.73434571e-03],
       [6.48072305e-03, 1.97025086e-03, 5.49803551e-03, ...,
        6.49826950e-01, 9.71410499e-01, 6.96288990e-01],
       [9.95734012e-01, 9.95696931e-01, 9.28008397e-01, ...,
        2.42384687e-05, 2.06173648e-04, 8.18576980e-02]])

In [36]:
h2.shape

(10, 5000)